administrator/urls.py
from django.urls import path
from .views import *

app_name = 'administrator'

urlpatterns = [

    path('', landing, name="landing"),

]

bakery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrator.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *
app_name='cart'
urlpatterns=[
    path('', cart_view, name='cart_view'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('remove_cart/<int:id>/', remove_cart, name='remove_cart'),
    path('add_single/<int:id>/', add_single, name='add_single'),
    path('remove_single/<int:id>/', remove_single, name='remove_single'),

]

cart/models.py
from django.db import models
from accounts.models import User
from administrator.models import post
from django.forms import ModelForm

# Create your models here.


class Cart(models.Model):
    product = models.ForeignKey(post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="تعداد")
    class Meta:
        verbose_name = "سبد خرید"
        verbose_name_plural = "سبد خرید"


class cartForm(ModelForm):
    class Meta:
        model = Cart
        fields = ['quantity']

cart/views.py
from django.shortcuts import render, redirect
from .models import Cart
from administrator.models import post
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='accounts:login')
def cart_view(request):
    card = Cart.objects.filter(user_id=request.user.user_id)
    user = request.user
    total = 0
    for cards in card:
        total += cards.quantity * cards.product.price

    context ={
        'card': card,
        'total': total,
        'user': user
    }
    return render(request, 'cart/shopping-cart.html', context)


@login_required(login_url='accounts:login')
def add_to_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    quantity =1

    if Cart.objects.filter(user_id=request.user.user_id, product_id=id).exists():
        card=Cart.objects.get(user_id=request.user.id, product_id=id)
        card.quantity += 1
        card.save()
        return redirect(url)
    else:
        card = Cart.objects.create(quantity=quantity, product_id=id, user_id=request.user.user_id)

        card.save()
        return redirect(url)


@login_required(login_url='accounts:login')
def remove_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    card = Cart.objects.get(id=id)
    card.delete()
    return redirect(url)

@login_required(login_url='accounts:login')
def add_single(request, id):
    url = request.META.get('HTTP_REFERER')
    cart = Cart.objects.get(id=id)
    prudoct = post.objects.get(id=cart.product.id)
    if prudoct.count > cart.quantity:
        cart.quantity += 1
        cart.save()
        return redirect(url)
    else:
        return redirect(url)


@login_required(login_url='accounts:login')
def remove_single(request, id):
    url = request.META.get('HTTP_REFERER')
    cart = Cart.objects.get(id=id)
    if cart.quantity < 2:
        cart.delete()
        return redirect(url)
    else:
        cart.quantity-=1
        cart.save()
        return redirect(url)

cart/templates/cart/shopping-cart.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shopping Cart</title>
    <link rel="stylesheet" href="{% static 'cart/css/style.css' %}" media="screen" title="no title" charset="utf-8">

    <link rel="stylesheet" href="{% static 'cart/css/shoping.css' %}" media="screen" title="no title" charset="utf-8">
    <script src="https://code.jquery.com/jquery-2.2.4.js" charset="utf-8"></script>
    <meta name="robots" content="noindex,follow" />
          <style>
        .header{
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  padding-bottom: 2rem;
  display: flex;
  flex-direction: row-reverse;
  justify-content: space-between;
  align-items: center;
}
.header .back{
    margin-right: 5%;
    color: black;
  background-color: rgb(76, 173, 115);
  width: 2rem;
  height: 2rem;
}



    </style>

  </head>






  <body>
  <header>
      <div class="header">
          <a href="{% url 'administrator:landing' %}" class="back" >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
            </svg>

          </a>
      </div>
    </header>

    <div class="shopping-cart">
      <!-- Title -->
      <div clas="title">
سبد خرید  </div>

        {% for cards in card %}
            <div class="item">
                <a href="{% url 'cart:remove_cart' cards.id %}" class="buttons">
          <span class="delete-btn"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
          </span>
        </a>

                <div class="description">
          <span>{{ cards.product}}</span>
{#          <span>Bball High</span>#}
{#          <span>White</span>#}
        </div>
                <div class="quantity"></div>


                <div class="quantity">

            <a href="{% url 'cart:add_single' cards.id %}" class="counter-btn">+</a>


          <input type="text" name="name" value="{{ cards.quantity }}">
            <a href="{% url 'cart:remove_single' cards.id %}" class="counter-btn">-</a>
        </div>
                <div class="quantity"></div>

                <div class="total-price">${% widthratio cards.quantity 1 cards.product.price %}</div>
      </div>
        {% endfor %}



        <div class="item">

            <h2 style="  color: #43484D;">مجموع</h2>

                <div class="quantity"></div>
                <div class="quantity"></div>



        <div class="total-price" dir="rtl"> <span>تومان</span>{{total}}</div>
      </div>





    </div>
{#    {% if card.exists %}#}
{#        <div class="login-form-container">#}
{##}
{##}
{#    <form action="{% url 'order:create_order' %}" method="POST" dir="rtl">#}
{#        {% csrf_token %}#}
{##}
{#        <h3>سفارش</h3>#}
{#        <span>تلفن</span>#}
{#        <input type="number" name="phone" class="box" value="{{ user.phone }}" required >#}
{#        <span>نام</span>#}
{#        <input type="text" name="first_name" class="box" value="{{ user.first_name}}" required>#}
{#        <span>فامیل </span>#}
{#        <input type="text" name="last_name" class="box" value="{{ user.last_name }}" required >#}
{#        <span>آدرس</span>#}
{#        <input type="text" name="address" class="box" required >#}
{##}
{#        <input type="submit" value="سفارش" class="btn">#}
{##}
{#    </form>#}
{##}
{#</div>#}
{#    {% endif %}#}
{##}






    <script type="text/javascript">
      $('.minus-btn').on('click', function(e) {
    		e.preventDefault();
    		var $this = $(this);
    		var $input = $this.closest('div').find('input');
    		var value = parseInt($input.val());

    		if (value > 1) {
    			value = value - 1;
    		} else {
    			value = 0;
    		}

        $input.val(value);

    	});

    	$('.plus-btn').on('click', function(e) {
    		e.preventDefault();
    		var $this = $(this);
    		var $input = $this.closest('div').find('input');
    		var value = parseInt($input.val());

    		if (value < 100) {
      		value = value + 1;
    		} else {
    			value =100;
    		}

    		$input.val(value);
    	});

      $('.like-btn').on('click', function() {
        $(this).toggleClass('is-active');
      });
    </script>
  </body>
</html>