accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [

    path('register', Register, name="register"),
    path('seller_register', RegisterSeller, name="sellerRegister"),
    path('login', Login, name="login"),
    path('logout', Logout, name="logout"),
    path('edit_profile', editProfile, name="edit_profile"),
    path('seller_edit_profile', SellerEditProfile, name="seller_edit_profile"),
    path('profile_view', profile, name="profile_view"),
    path('login_phone/', login_phone, name="login_phone"),
    path('verify_login_phone/', verify_login_phone, name="verify_login_phone"),

]

bakery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrator.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *
app_name='cart'
urlpatterns=[
    path('', cart_view, name='cart_view'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('remove_cart/<int:id>/', remove_cart, name='remove_cart'),
    path('add_single/<int:id>/', add_single, name='add_single'),
    path('remove_single/<int:id>/', remove_single, name='remove_single'),

]

accounts/models.py
from django.db import models

# Create your models here.


from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.


class UserManager(BaseUserManager):
    def create_user(self, phone, username, password, role):
        if not phone:
            raise ValueError('please enter an phone')

        if not username:
            raise ValueError('please enter an username')

        user = self.model(phone=phone, username=username, role=role)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, username, password,  role='ADMIN'):
       user = self.create_user(phone, username, password, role)
       user.is_admin = True
       user.save(using=self._db)
       return user


class User(AbstractBaseUser):
    ROLE_CHOICES =(
        ('SELLER', 'Seller'),
        ('COSTUMER', 'costumer'),
        ('ADMIN', 'admin'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    username = models.CharField(max_length=50)
    phone = models.IntegerField(unique=True)
    user_id = models.AutoField(primary_key=True, auto_created=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['username']
    objects = UserManager()

    def __str__(self):
        return self.phone

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin




class CostumerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    city = models.CharField(max_length=200)
    address = models.TextField()
    verify_phone = models.BooleanField(default=False)


def save_profile_user(sender, instance, **kwargs):
    if kwargs['created'] and instance.role == "COSTUMER":
        profile_user = CostumerProfile(user=instance)
        profile_user.save()


post_save.connect(save_profile_user, sender=User)




class BakeryType(models.Model):
    type = models.CharField(max_length=100)
    def __str__(self):
        return self.type


class SellerProfile(models.Model):
    STATUS_CHOICES =(
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
        ('mon', 'Monday'),
        ('tue', 'Tuesday'),
        ('wed', 'Wednesday'),
        ('thu', 'Thursday'),
        ('fri', 'Friday'),
    )
    type = models.ManyToManyField(BakeryType, blank=True, related_name="typeof")
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='seller')
    first_name = models.CharField(max_length=50)
    Holiday = models.CharField(max_length=3, choices=STATUS_CHOICES)
    last_name = models.CharField(max_length=50)
    bakeryPhone = models.IntegerField(null=True)
    city = models.CharField(max_length=200)
    address = models.TextField()
    verify_phone = models.BooleanField(default=False)
    def __str__(self):
        return self.user.phone


def save_seller_profile(sender, instance, **kwargs):
    if kwargs['created'] and instance.role == "SELLER":
        seller_profile = SellerProfile(user=instance)
        seller_profile.save()


post_save.connect(save_seller_profile, sender=User)

accounts/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['phone', 'username', 'role']

    def clean_password2(self):
        data = self.cleaned_data
        if data['password2'] and data['password1'] and data['password2'] != data['password1']:
            raise forms.ValidationError('PLEASE CHECK THE PASSWORD')
        return data['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class CostumerProfileUpdate(forms.ModelForm):
    class Meta:
        model = CostumerProfile
        fields = ['first_name', 'last_name', 'city', 'address']


class SellerProfileUpdate(forms.ModelForm):
    class Meta:
        model = SellerProfile
        fields = ['first_name', 'last_name', 'city', 'address', 'bakeryPhone', 'Holiday', 'type']



class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields = ['phone', 'username']

class LoginPhoneForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['phone']


class CodePhoneForm(forms.ModelForm):
    class Meta:
        model = CostumerProfile
        fields = ['verify_phone']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
from kavenegar import *
import random
from django.http import HttpResponse

# Create your views here.


def Register(request):
    if request.user.is_authenticated:
        return redirect('administrator:landing')
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['username'], phone=data['phone'], password=data['password2'],
                                            role=data['role'])

            user.save()
            return redirect('accounts:login')
    else:
        form = UserCreateForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)


def RegisterSeller(request):
    if request.user.is_authenticated:
        return redirect('administrator:landing')
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            print(2)
            data = form.cleaned_data
            user = User.objects.create_user(username=data['username'],phone=data['phone'], password=data['password2'],
                                            role=data['role'])
            user.save()
            return redirect('accounts:login')
    else:
        form = UserCreateForm()
    context = {'form': form}
    return render(request, 'accounts/signupSellers.html', context)


def Login(request):
    if request.user.is_authenticated:
        return redirect('administrator:landing')
    if request.method == 'POST':
        username = request.POST.get('phone')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:

            login(request, user)
            return redirect("administrator:landing")
        else:

            return render(request, 'accounts/login.html')
    else:
        return render(request, 'accounts/login.html', {})


@login_required(login_url='accounts:login')
def Logout(request):
    logout(request)
    return redirect('accounts:login')


@login_required(login_url='accounts:login')
def profile(request):
    if request.user.role == "COSTUMER":
        context = {
            'profile': CostumerProfile.objects.get(user_id=request.user.user_id)
        }
        return render(request, 'accounts/profile.html', context)
    else:
        context = {
            'profile': SellerProfile.objects.get(user_id=request.user.user_id)
        }
        return render(request, 'accounts/bakeryProfile.html', context)


@login_required(login_url='accounts:login')
def editProfile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        user_profile = CostumerProfileUpdate(request.POST, instance=request.user.profile)
        if user_profile.is_valid() or user_form.is_valid():
            user_form.save()
            user_profile.save()
            return redirect('accounts:profile_view')

    else:
        user_form = UserUpdateForm(instance=request.user)
        user_profile = CostumerProfileUpdate(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'user_profile': user_profile,
    }
    return render(request, 'accounts/edit_profile.html', context)


@login_required(login_url='accounts:login')
def SellerEditProfile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        user_profile = SellerProfileUpdate(request.POST, instance=request.user.seller)
        if user_profile.is_valid() or user_form.is_valid():
            user_form.save()
            user_profile.save()
            return redirect('accounts:profile_view')


    else:
        user_form = UserUpdateForm(instance=request.user)
        user_profile = SellerProfileUpdate(instance=request.user.seller)
        type = BakeryType.objects.all()
    context = {
        'user_form': user_form,
        'user_profile': user_profile,
    }
    return render(request, 'accounts/seller_edit_profile.html', context)


def login_phone(request):
    if request.method == 'POST':
        print('12')
        form = request.POST.get('phone')
        print(form)
        if form:
            print('13')
            data = form
            global phone, random_code
            phone = f"{data}"
            random_code = random.randint(1000, 9999)
            print(random_code)
            sms = KavenegarAPI(
                "***")  #
            params = {
                'sender': '10003330033033',  # 10003330033033
                'receptor': phone,  # 09001099069
                'message': f' {random_code} سلام این اولین تست است ',
            }
            response = sms.sms_send(params)
            print(response
                  )
            return redirect('accounts:verify_login_phone')
        else:
            return HttpResponse('not valid')
    else:
        form = LoginPhoneForm()
    context = {
        'form': form,
    }
    print('11')
    return render(request, 'accounts/phone/login-phone.html', context)


def verify_login_phone(request):
    if request.method == 'POST':
        form = CodePhoneForm(request.POST)
        if form.is_valid():
            if str(random_code) == form.cleaned_data['verify_phone']:
                profile = User.objects.filter(id=request.user.id).update(phone=phone)
                global verify
                verify = True
                return redirect('accounts:home')
            else:
                messages.error(request, 'کد وارد شده اشتباه است')
    else:
        form = CodePhoneForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/phone/verify-login-phone.html', context)

# < select
# name = "category"
# id = "category"
#
#
# class ="w-75 text-center mt-1 mb-2" style="height: 2.2rem; display:flex; border: 1px solid rgba(0,0,0,0.22); border-radius: 25px" >
#

# { %
# for cate in category %}
# < option
# value = "{{ cate.id }}" > {{cate.title}} < / option >
# { % endfor %}
# < / select >
#
#

accounts/templates/accounts/bakeryProfile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="{% static 'accounts/profile/css/profile.css' %}">
    <title>profile</title>
</head>

<body>
    {% include 'administrator/header.html' %}

    <div class="row py-5 my-6 py-6 px-4" style="margin-top: 3rem">
        <div class="col-md-5 mx-auto">
            <!-- Profile widget -->
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-0 pb-4 cover">
                    <div class="media align-items-end profile-head">
                        <div class="profile mr-3">
                            <img src="{% static 'administrator/img/pic-5.png' %}" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                                <a href="{% url 'accounts:seller_edit_profile' %}" class="hh btn btn-outline-dark btn-sm btn-block">Edit profile</a></div>
                        <div class="media-body mb-5 ">
                            <h4 class="mt-0 mb-0">{{ profile.first_name }}</h4>
                            <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>{{ profile.city }}</p>
                        </div>
                    </div>
                </div>
                <div class="bg-light p-4 d-flex justify-content-end text-center">
                    <h4 class="mt-0 mr-2 mb-0">{{ profile.user.phone }}</h4>

                </div>
                <div class="px-4 py-3">
                    <div class="back p-4 rounded shadow-sm  ">
                        <p class="font-italic mb-0">{{ profile.address }}</p>
                    </div>
                </div>
                <div class="px-4 py-3">
                    <div class="back p-4 rounded shadow-sm  ">
                        <p class="font-italic mb-0">{{ profile.Holiday }}روز تعطیل</p>
                    </div>
                </div>
                {% load static %}

            </div>
        </div>
    </div>
</body>

</html>

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V2</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "accounts/login/css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "accounts/login/css/main.css" %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST" >
                    {% csrf_token %}
					<span class="login100-form-title p-b-26">
						خوش آمدید
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<div class="wrap-input100 validate-input" >
						<input class="input100" type="number" name="phone">
						<span class="focus-input100" data-placeholder="تلفن"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password">
						<span class="focus-input100" data-placeholder="رمز عبور"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								ورود
							</button>
						</div>
					</div>

					<div class="text-center p-t-115">
						<span class="txt1">
							اکانت ندارید؟
						</span>

						<a class="txt2" href="{% url 'accounts:register' %}">
							 ثبت نام کاربر
						</a>
                        <br/>
                        <a class="txt2" href="{% url 'accounts:sellerRegister' %}">
							 ثبت نام فروشنده
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "accounts/login/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "accounts/login/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/js/main.js" %}"></script>

</body>
</html>

accounts/templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="{% static 'accounts/profile/css/profile.css' %}">
    <title>profile</title>
</head>

<body>
    {% include 'administrator/header.html' %}

    <div class="row py-5 my-6 py-6 px-4" style="margin-top: 3rem">
        <div class="col-md-5 mx-auto">
            <!-- Profile widget -->
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-0 pb-4 cover">
                    <div class="media align-items-end profile-head">
                        <div class="profile mr-3">
                            <img src="{% static 'administrator/img/pic-5.png' %}" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                                <a href="{% url 'accounts:edit_profile' %}" class="hh btn btn-outline-dark btn-sm btn-block">Edit profile</a></div>
                        <div class="media-body mb-5 ">
                            <h4 class="mt-0 mb-0">{{ profile.first_name }}</h4>
                            <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>{{ profile.city }}</p>
                        </div>
                    </div>
                </div>
                <div class="bg-light p-4 d-flex justify-content-end text-center">
                    <h4 class="mt-0 mr-2 mb-0">{{ profile.user.phone }}</h4>

                </div>
                <div class="px-4 py-3" >
                    <div  style="position: relative" class="back p-4 rounded shadow-sm   ">
                        <p class="font-italic mb-0" style="position: absolute; right: 10px; top: 10px" >آدرس:   {{ profile.address }}</p>
                    </div>
                </div>
{#                <div class="py-4 px-4">#}
{#                    <div class="d-flex align-items-center justify-content-between mb-3">#}
{#                        <h5 class="mb-0">سفارشات اخیر</h5>#}
{#                    </div>#}
{#                    <div class="row">#}
{#                        {% for posts in post %}#}
{#                            <div class="col-lg-6 mb-5 pr-lg-1  "><a href="{% url 'administrator:buy' posts.post.id %}"><img#}
{#                                src="{{ posts.post.image.url }}"#}
{#                                alt="" class="img-fluid rounded shadow-sm"></a>#}
{#                                <h4 class="mt-0 mb-0">{{ posts.post.title}}</h4>#}
{##}
{#                            </div>#}
{##}
{#                        {% endfor %}#}
{##}
{##}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>
    </div>
</body>

</html>

accounts/templates/accounts/seller_edit_profile.html
{% load static %}
<!DOCTYPE html >
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'administrator/edit_profile/css/edit_profile.css' %}">
    <title>profile</title>
</head>
<body>
    <div class="container rounded bg-white mt-5">
        <div class="row">
            <div class="col-md-12 border">
                <form method="POST" class="p-3 py-5">
                    {% csrf_token %}
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h6 class="text-right">Edit Profile</h6>

                        <div class="d-flex flex-row align-items-center back">
                            <a class="nav__link" style="color: #EAA636FF" href="{% url 'accounts:profile_view' %}"><h6>Back to home</h6></a>
                            <i style="color: #EAA636FF" class="fa fa-long-arrow-left mr-1 mb-1 "></i>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6"><input type="text" name="first_name" class="form-control" placeholder="نام" value=""></div>
                        <div class="col-md-6"><input type="text" name="last_name" class="form-control" value="" placeholder="نام خانوادگی"></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6"><input type="number" name="phone" class="form-control" placeholder="تلفن" value=""></div>
                        <div class="col-md-6"><input type="text" name="username" class="form-control" value="" placeholder="نام کاربری"></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6"><select name="Holiday" class="form-control" required="" id="id_Holiday">
                            {% for holiday in user_profile.Holiday %}
                                {{ holiday }}
                            {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                            <select name="type" style="height:60px" class="form-control" id="id_type" multiple="">
                                {% for types in user_profile.type %}

                                    {{ types }}

                                {% endfor %}


                            </select>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-4"><input type="text" name="city" class="form-control" placeholder="شهر" value=""></div>
                        <div class="col-md-4"><input type="text" name="address" class="form-control" value="" placeholder="آدرس"></div>
                        <div class="col-md-4"><input type="text" name="bakeryPhone" class="form-control" placeholder="شماره نانوایی" value=""></div>

                    </div>

                    <div class="mt-5 text-right"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
                </form>
            </div>

        </div>
    </div>
</body>
</html>
{#{{ user_profile }}#}

accounts/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V2</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "accounts/login/css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "accounts/login/css/main.css" %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST" >
                    {% csrf_token %}
					<span class="login100-form-title p-b-26">
                        ثبت نام
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<div class="wrap-input100 validate-input" >
						<input class="input100" type="number" name="phone">
						<span class="focus-input100" data-placeholder="تلفن"></span>
					</div>
                    <div class="wrap-input100 validate-input" >
						<input class="input100" type="text" name="username">
						<span class="focus-input100" data-placeholder="نام کاربری"></span>
					</div>
                    <div style="display: none" class="wrap-input100 validate-input" >
                        <select name="role" required="" id="id_role">

                            <option value="COSTUMER" selected>COSTUMER</option>


                        </select>
					</div>
                    <div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password1">
						<span class="focus-input100" data-placeholder="رمز عبور"></span>
					</div>
					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password2">
						<span class="focus-input100" data-placeholder="تکرا رمز عبور"></span>
					</div>

					<div  class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								ساخت اکانت
							</button>
						</div>
					</div>

					<div class="text-center p-t-15">
                        <span class="txt1">
							اکانت دارید؟
						</span>
                        <a class="txt2" href="{% url 'accounts:login' %}">
							ورود
						</a>



					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "accounts/login/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "accounts/login/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "accounts/login/js/main.js" %}"></script>

</body>
</html>