accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [

    path('register', Register, name="register"),
    path('seller_register', RegisterSeller, name="sellerRegister"),
    path('login', Login, name="login"),
    path('logout', Logout, name="logout"),
    path('edit_profile', editProfile, name="edit_profile"),
    path('seller_edit_profile', SellerEditProfile, name="seller_edit_profile"),
    path('profile_view', profile, name="profile_view"),
    path('login_phone/', login_phone, name="login_phone"),
    path('verify_login_phone/', verify_login_phone, name="verify_login_phone"),

]

administrator/urls.py
from django.urls import path
from .views import *

app_name = 'administrator'

urlpatterns = [

    path('', landing, name="landing"),

]

bakery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrator.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *
app_name='cart'
urlpatterns=[
    path('', cart_view, name='cart_view'),
    path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
    path('remove_cart/<int:id>/', remove_cart, name='remove_cart'),
    path('add_single/<int:id>/', add_single, name='add_single'),
    path('remove_single/<int:id>/', remove_single, name='remove_single'),

]

administrator/models.py
from django.db import models

# Create your models here.


class post(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post")
    title = models.CharField(max_length=100)
    description = models.TextField()
    count = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=0)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='images')
    def __str__(self):
        return self.title

administrator/views.py
from django.shortcuts import render

from administrator.models import post


# Create your views here.

def landing(requests):
    context={
        "post": post.objects.all()
    }
    return render(requests, "administrator/product.html", context)

administrator/templates/administrator/header.html
{% load static %}
<!DOCTYPE html>
<head>
        <link href="{% static "administrator/css/nav.css" %}" rel="stylesheet">
</head>
<html lang="en">

<header class="header" id="header">
        <nav class="nav container">

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item">
                            <a href="{% url 'administrator:landing' %}" class="nav__link ">
                                <i class='bx bx-home-alt nav__icon'></i>
                                <span class="nav__name">خانه</span>
                            </a>
                        </li>
                        {% if request.user.exists %}

                            <li class="nav__item">
                                <a href="{% url 'accounts:login' %}" class="nav__link">
                                    <i class='bx bx-book-alt nav__icon'></i>
                                    <span class="nav__name">ورود</span>
                                </a>
                            </li>

                        {% else %}
                            <li class="nav__item">
                                <a href="{% url 'accounts:profile_view' %}" class="nav__link">
                                    <i class='bx bx-book-alt nav__icon'></i>
                                    <span class="nav__name">پروفایل</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if request.user.role == "COSTUMER" %}

                            <li class="nav__item">
                                <a href="{% url 'cart:cart_view' %}" class="nav__link ">
                                    <i class='bx bx-home-alt nav__icon'></i>
                                    <span class="nav__name">سبد خرید</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if request.user.is_authenticated  %}

                            <li class="nav__item">
                                <a href="{% url 'accounts:logout' %}" class="nav__link ">
                                    <i class='bx bx-home-alt nav__icon'></i>
                                    <span class="nav__name">خروج</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </div>


            </nav>
    </header>

</html>

administrator/templates/administrator/product.html
{% load static %}
<html lang="en"><head>

  <meta charset="UTF-8">

<link rel="apple-touch-icon" type="image/png" href="https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png">
<meta name="apple-mobile-web-app-title" content="CodePen">

<link rel="shortcut icon" type="image/x-icon" href="https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico">

<link rel="mask-icon" type="image/x-icon" href="https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg" color="#111">



  <title>CodePen - Shopping cart JS</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>



    <!-- Libraries Stylesheet -->
    <link href="{% static "administrator/lib/animate/animate.min.css" %}" rel="stylesheet">
    <link href="{% static "administrator/lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static "administrator/css/bootstrap.min.css" %}" rel="stylesheet">

    <link href="{% static "administrator/css/style.css" %}" rel="stylesheet">



</head>

<body translate="no">
    {% include 'administrator/header.html' %}

<!-- Main -->
    <div style="margin-top: 100px" class="  bg-light my-6  py-6 pt-0">
        <div class="container">
            <div class="row g-4">
                {% for posts in post %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp" >
                        <div class="product-item d-flex flex-column bg-white rounded overflow-hidden h-100">

                                <div class="position-relative mt-auto">
                                <img class="img-fluid" src="{{ posts.image.url }}" alt="">

                                </div>
                                <div class=" p-5">


                                    <div style="display: flex; justify-content: space-between">
                                        <h3 class="mb-3">{{ posts.title }}</h3>
                                        <div>

                                            <div class="d-inline-block " STYLE="margin-right: 10px">{{ posts.price }}</div>
                                        </div>
                                    </div>
                                    <div style="display: flex; justify-content: space-between">
                                        <span>{{ posts.description }}</span>
                                        <a href="{% url 'cart:add_to_cart' posts.id %}"  class="add-to-cart border border-primary   btn  btn-outline-primary ">Add to cart</a>

                                </div>

                                </div>


                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>


</body></html>